# Worksheet 0

In [9]:
import numpy as np
import time

## TO DO 1
### Qn 1

In [10]:
def convert_units(conversion_type, value):
    """Convert between supported length, weight, and volume units."""
    if conversion_type == "m_to_ft":
        return value * 3.28084
    elif conversion_type == "ft_to_m":
        return value / 3.28084
    elif conversion_type == "kg_to_lbs":
        return value * 2.20462
    elif conversion_type == "lbs_to_kg":
        return value / 2.20462
    elif conversion_type == "l_to_gal":
        return value * 0.264172
    elif conversion_type == "gal_to_l":
        return value / 0.264172
    else:
        raise ValueError("Unsupported conversion type.")


def run_unit_converter_program():
    print("Choose a conversion type:")
    print("1. meters to feet")
    print("2. feet to meters")
    print("3. kilograms to pounds")
    print("4. pounds to kilograms")
    print("5. liters to gallons")
    print("6. gallons to liters")

    choice_map = {
        "1": "m_to_ft",
        "2": "ft_to_m",
        "3": "kg_to_lbs",
        "4": "lbs_to_kg",
        "5": "l_to_gal",
        "6": "gal_to_l"
    }

    choice = input("Enter your choice (1-6): ")

    try:
        if choice not in choice_map:
            raise ValueError("Invalid conversion choice.")

        value = float(input("Enter the value to convert: "))
        result = convert_units(choice_map[choice], value)
        print("Converted value:", result)
    except ValueError as error:
        print("Error:", error)


print("Sample conversions:")
print("5 meters to feet =", convert_units("m_to_ft", 5))
print("10 kilograms to pounds =", convert_units("kg_to_lbs", 10))
print("3 liters to gallons =", convert_units("l_to_gal", 3))


Sample conversions:
5 meters to feet = 16.4042
10 kilograms to pounds = 22.0462
3 liters to gallons = 0.792516


### Qn 2

In [11]:
def find_sum(numbers):
    """Return sum of all numbers in the list."""
    total = 0
    for number in numbers:
        total += number
    return total


def find_average(numbers):
    """Return average of numbers in the list."""
    if len(numbers) == 0:
        raise ValueError("The list is empty.")
    return find_sum(numbers) / len(numbers)


def find_maximum(numbers):
    """Return maximum value in the list."""
    if len(numbers) == 0:
        raise ValueError("The list is empty.")

    maximum = numbers[0]
    for number in numbers:
        if number > maximum:
            maximum = number
    return maximum


def find_minimum(numbers):
    """Return minimum value in the list."""
    if len(numbers) == 0:
        raise ValueError("The list is empty.")

    minimum = numbers[0]
    for number in numbers:
        if number < minimum:
            minimum = number
    return minimum


def run_math_program():
    print("Choose an operation:")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    choice = input("Enter your choice (1-4): ")

    try:
        raw_numbers = input("Enter numbers separated by spaces: ")
        parts = raw_numbers.split()

        if len(parts) == 0:
            raise ValueError("You entered an empty list.")

        numbers = []
        for part in parts:
            numbers.append(float(part))

        if choice == "1":
            print("Sum =", find_sum(numbers))
        elif choice == "2":
            print("Average =", find_average(numbers))
        elif choice == "3":
            print("Maximum =", find_maximum(numbers))
        elif choice == "4":
            print("Minimum =", find_minimum(numbers))
        else:
            print("Invalid operation choice.")
    except ValueError as error:
        print("Error:", error)


sample_numbers = [4, 8, 15, 16, 23, 42]
print("Sample numbers:", sample_numbers)
print("Sum =", find_sum(sample_numbers))
print("Average =", find_average(sample_numbers))
print("Maximum =", find_maximum(sample_numbers))
print("Minimum =", find_minimum(sample_numbers))


Sample numbers: [4, 8, 15, 16, 23, 42]
Sum = 108
Average = 18.0
Maximum = 42
Minimum = 4


### Qn 3

In [12]:
def extract_every_other(lst):
    return lst[::2]


def get_sublist(lst, start, end):
    return lst[start:end + 1]


def reverse_list(lst):
    return lst[::-1]


def remove_first_last(lst):
    return lst[1:-1]


def get_first_n(lst, n):
    return lst[:n]


def get_last_n(lst, n):
    return lst[-n:]


def reverse_skip(lst):
    return lst[-2::-2]


example_list = [1, 2, 3, 4, 5, 6]
print("Original list:", example_list)
print("1. Every other element:", extract_every_other(example_list))
print("2. Sublist from index 2 to 4:", get_sublist(example_list, 2, 4))
print("3. Reversed list:", reverse_list([1, 2, 3, 4, 5]))
print("4. Remove first and last:", remove_first_last([1, 2, 3, 4, 5]))
print("5. First 3 elements:", get_first_n([1, 2, 3, 4, 5], 3))
print("6. Last 2 elements:", get_last_n([1, 2, 3, 4, 5], 2))
print("7. Reverse skip:", reverse_skip(example_list))

Original list: [1, 2, 3, 4, 5, 6]
1. Every other element: [1, 3, 5]
2. Sublist from index 2 to 4: [3, 4, 5]
3. Reversed list: [5, 4, 3, 2, 1]
4. Remove first and last: [2, 3, 4]
5. First 3 elements: [1, 2, 3]
6. Last 2 elements: [4, 5]
7. Reverse skip: [5, 3, 1]


### Qn 4

In [13]:
def flatten(lst):
    result = []
    for item in lst:
        if isinstance(item, list):
            for value in flatten(item):
                result.append(value)
        else:
            result.append(item)
    return result


def access_nested_element(lst, indices):
    current = lst
    for index in indices:
        current = current[index]
    return current


def sum_nested(lst):
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total


def remove_element(lst, elem):
    result = []
    for item in lst:
        if isinstance(item, list):
            result.append(remove_element(item, elem))
        else:
            if item != elem:
                result.append(item)
    return result


def find_max(lst):
    flat_list = flatten(lst)
    maximum = flat_list[0]
    for item in flat_list:
        if item > maximum:
            maximum = item
    return maximum


def count_occurrences(lst, elem):
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        else:
            if item == elem:
                count += 1
    return count


def deep_flatten(lst):
    return flatten(lst)


def average_nested(lst):
    flat_list = flatten(lst)
    if len(flat_list) == 0:
        raise ValueError("Nested list is empty.")
    return sum(flat_list) / len(flat_list)


nested_example_1 = [[1, 2], [3, 4], [5]]
nested_example_2 = [[1, 2], [3, [4, 5]], 6]
nested_example_3 = [[1, 2], [3, 2], [4, 5]]
nested_example_4 = [[[1, 2], [3, 4]], [[5, 6], [7, 8]]]

print("1. Flatten:", flatten(nested_example_1))
print("2. Access nested element:", access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))
print("3. Sum nested:", sum_nested(nested_example_2))
print("4. Remove element 2:", remove_element(nested_example_3, 2))
print("5. Find max:", find_max(nested_example_2))
print("6. Count occurrences of 2:", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))
print("7. Deep flatten:", deep_flatten(nested_example_4))
print("8. Average nested:", average_nested([[1, 2], [3, 4], [5, 6]]))

1. Flatten: [1, 2, 3, 4, 5]
2. Access nested element: 6
3. Sum nested: 21
4. Remove element 2: [[1], [3], [4, 5]]
5. Find max: 6
6. Count occurrences of 2: 3
7. Deep flatten: [1, 2, 3, 4, 5, 6, 7, 8]
8. Average nested: 3.5


## TO DO 2
### Qn 1

In [14]:
print("Problem 1: Array Creation")
empty_array = np.empty((2, 2))
print("1. Empty 2x2 array:\n", empty_array)

ones_array = np.ones((4, 2))
print("2. Ones 4x2 array:\n", ones_array)

full_array = np.full((2, 3), 7, dtype=int)
print("3. Full array:\n", full_array)

base_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=float)
zeros_like_array = np.zeros_like(base_array)
print("4. Zeros like base array:\n", zeros_like_array)

ones_like_array = np.ones_like(base_array)
print("5. Ones like base array:\n", ones_like_array)

new_list = [1, 2, 3, 4]
array_from_list = np.array(new_list)
print("6. NumPy array from list:\n", array_from_list)

print("\nProblem 2: Array Manipulation")
array_10_to_49 = np.arange(10, 50)
print("1. Array from 10 to 49:\n", array_10_to_49)

matrix_3x3 = np.arange(9).reshape(3, 3)
print("2. 3x3 matrix from 0 to 8:\n", matrix_3x3)

identity_matrix = np.eye(3)
print("3. 3x3 identity matrix:\n", identity_matrix)

random_array_30 = np.random.random(30)
print("4. Random array of size 30:\n", random_array_30)
print("   Mean:", random_array_30.mean())

random_array_10x10 = np.random.random((10, 10))
print("5. 10x10 random array:\n", random_array_10x10)
print("   Minimum:", random_array_10x10.min())
print("   Maximum:", random_array_10x10.max())

zero_array = np.zeros(10)
zero_array[4] = 1
print("6. Zero array with 5th element replaced by 1:\n", zero_array)

arr = np.array([1, 2, 0, 0, 4, 0])
print("7. Reversed array:\n", arr[::-1])

border_array = np.ones((5, 5), dtype=int)
border_array[1:-1, 1:-1] = 0
print("8. 2D array with 1 on border and 0 inside:\n", border_array)

checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("9. 8x8 checkerboard matrix:\n", checkerboard)


Problem 1: Array Creation
1. Empty 2x2 array:
 [[23. 51.]
 [13. 29.]]
2. Ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
3. Full array:
 [[7 7 7]
 [7 7 7]]
4. Zeros like base array:
 [[0. 0. 0.]
 [0. 0. 0.]]
5. Ones like base array:
 [[1. 1. 1.]
 [1. 1. 1.]]
6. NumPy array from list:
 [1 2 3 4]

Problem 2: Array Manipulation
1. Array from 10 to 49:
 [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
2. 3x3 matrix from 0 to 8:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
3. 3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
4. Random array of size 30:
 [0.25555198 0.48032948 0.14229203 0.61834115 0.68451091 0.75447492
 0.45753069 0.34405443 0.878902   0.11342305 0.61709815 0.73625143
 0.59425183 0.13336185 0.63042465 0.43362174 0.66866566 0.27130167
 0.29530101 0.48884195 0.79143474 0.21093907 0.58762853 0.51150417
 0.53637712 0.95617372 0.95984002 0.20653855 0.52627384 0.8120148 ]
   Mean: 0.5232418379540376
5. 10x10

### Qn 2

In [15]:
print("Problem 3: Array Operations")
x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

print("x:\n", x)
print("y:\n", y)
print("v:\n", v)
print("w:\n", w)

print("1. x + y:\n", x + y)
print("2. x - y:\n", x - y)
print("3. x multiplied by 3:\n", x * 3)
print("   y multiplied by 2:\n", y * 2)
print("4. Square of x:\n", np.square(x))
print("   Square of y:\n", np.square(y))
print("5. Dot product v and w:", np.dot(v, w))
print("   Dot product x and v:\n", np.dot(x, v))
print("   Dot product x and y:\n", np.dot(x, y))
print("6. Concatenate x and y along rows:\n", np.concatenate((x, y), axis=0))
print("   Concatenate v and w along columns:\n", np.column_stack((v, w)))

print("7. Concatenate x and v:")
try:
    print(np.concatenate((x, v), axis=0))
except ValueError as error:
    print("Error:", error)

print("\nProblem 4: Matrix Operations")
A = np.array([[3, 4], [7, 8]], dtype=float)
B = np.array([[5, 3], [2, 1]], dtype=float)
I = np.eye(2)
A_inverse = np.linalg.inv(A)

print("A:\n", A)
print("B:\n", B)
print("1. A multiplied by A inverse:\n", np.dot(A, A_inverse))
print("   Is it close to I?", np.allclose(np.dot(A, A_inverse), I))

AB = np.dot(A, B)
BA = np.dot(B, A)
print("2. AB:\n", AB)
print("   BA:\n", BA)
print("   AB is equal to BA?", np.array_equal(AB, BA))

print("3. (AB)^T:\n", AB.T)
print("   B^T A^T:\n", np.dot(B.T, A.T))
print("   Are they equal?", np.allclose(AB.T, np.dot(B.T, A.T)))

coefficients = np.array([
    [2, -3, 1],
    [1, -1, 2],
    [3, 1, -1]
], dtype=float)
constants = np.array([-1, -3, 9], dtype=float)

inverse_coefficients = np.linalg.inv(coefficients)
solution_inverse_method = np.dot(inverse_coefficients, constants)
solution_using_inv = np.linalg.inv(coefficients).dot(constants)

print("\nSolution of the linear system using inverse method:")
print("x, y, z =", solution_inverse_method)
print("Solution using np.linalg.inv directly:")
print("x, y, z =", solution_using_inv)


Problem 3: Array Operations
x:
 [[1 2]
 [3 5]]
y:
 [[5 6]
 [7 8]]
v:
 [ 9 10]
w:
 [11 12]
1. x + y:
 [[ 6  8]
 [10 13]]
2. x - y:
 [[-4 -4]
 [-4 -3]]
3. x multiplied by 3:
 [[ 3  6]
 [ 9 15]]
   y multiplied by 2:
 [[10 12]
 [14 16]]
4. Square of x:
 [[ 1  4]
 [ 9 25]]
   Square of y:
 [[25 36]
 [49 64]]
5. Dot product v and w: 219
   Dot product x and v:
 [29 77]
   Dot product x and y:
 [[19 22]
 [50 58]]
6. Concatenate x and y along rows:
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
   Concatenate v and w along columns:
 [[ 9 11]
 [10 12]]
7. Concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

Problem 4: Matrix Operations
A:
 [[3. 4.]
 [7. 8.]]
B:
 [[5. 3.]
 [2. 1.]]
1. A multiplied by A inverse:
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
   Is it close to I? True
2. AB:
 [[23. 13.]
 [51. 29.]]
   BA:
 [[36. 44.]
 [13. 16.]]
   AB is equal to BA? False

### Qn 3

In [16]:
size = 1_000_000

list_a = list(range(size))
list_b = list(range(size))
array_a = np.array(list_a)
array_b = np.array(list_b)

start = time.time()
list_add_result = []
for i in range(size):
    list_add_result.append(list_a[i] + list_b[i])
list_add_time = time.time() - start
print("Python list addition time:", list_add_time, "seconds")

start = time.time()
array_add_result = array_a + array_b
array_add_time = time.time() - start
print("NumPy array addition time:", array_add_time, "seconds")

start = time.time()
list_mul_result = []
for i in range(size):
    list_mul_result.append(list_a[i] * list_b[i])
list_mul_time = time.time() - start
print("Python list multiplication time:", list_mul_time, "seconds")

start = time.time()
array_mul_result = array_a * array_b
array_mul_time = time.time() - start
print("NumPy array multiplication time:", array_mul_time, "seconds")

start = time.time()
list_dot_result = 0
for i in range(size):
    list_dot_result += list_a[i] * list_b[i]
list_dot_time = time.time() - start
print("Python list dot product time:", list_dot_time, "seconds")

start = time.time()
array_dot_result = np.dot(array_a, array_b)
array_dot_time = time.time() - start
print("NumPy array dot product time:", array_dot_time, "seconds")

print("\nSummary for the first three tests:")
print("Addition -> Python:", list_add_time, "NumPy:", array_add_time)
print("Multiplication -> Python:", list_mul_time, "NumPy:", array_mul_time)
print("Dot product -> Python:", list_dot_time, "NumPy:", array_dot_time)

run_full_matrix_test = False
matrix_size = 1000

if run_full_matrix_test:
    python_matrix_1 = []
    python_matrix_2 = []
    for i in range(matrix_size):
        row1 = []
        row2 = []
        for j in range(matrix_size):
            row1.append(i + j)
            row2.append(i - j)
        python_matrix_1.append(row1)
        python_matrix_2.append(row2)

    start = time.time()
    python_matrix_result = []
    for i in range(matrix_size):
        result_row = []
        for j in range(matrix_size):
            total = 0
            for k in range(matrix_size):
                total += python_matrix_1[i][k] * python_matrix_2[k][j]
            result_row.append(total)
        python_matrix_result.append(result_row)
    python_matrix_time = time.time() - start
    print("Python list matrix multiplication time:", python_matrix_time, "seconds")

    numpy_matrix_1 = np.array(python_matrix_1)
    numpy_matrix_2 = np.array(python_matrix_2)

    start = time.time()
    numpy_matrix_result = np.dot(numpy_matrix_1, numpy_matrix_2)
    numpy_matrix_time = time.time() - start
    print("NumPy matrix multiplication time:", numpy_matrix_time, "seconds")
else:
    print("\n1000x1000 matrix multiplication block skipped.")


Python list addition time: 0.12316584587097168 seconds
NumPy array addition time: 0.002235889434814453 seconds
Python list multiplication time: 0.11706829071044922 seconds
NumPy array multiplication time: 0.002227306365966797 seconds
Python list dot product time: 0.11339950561523438 seconds
NumPy array dot product time: 0.0012388229370117188 seconds

Summary for the first three tests:
Addition -> Python: 0.12316584587097168 NumPy: 0.002235889434814453
Multiplication -> Python: 0.11706829071044922 NumPy: 0.002227306365966797
Dot product -> Python: 0.11339950561523438 NumPy: 0.0012388229370117188

1000x1000 matrix multiplication block skipped.
